//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE_Project___Adaptive_Sorting_Algorithm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BE_Project___Adaptive_Sorting_Algorithm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [739, 6226, 10801, 14352, 15501, 19256, 22618, 24702, 25786, 29833, 2047, 2129, 4156, 16563, 18876, 21245, 25037, 27218, 27417, 32413, 4814, 5220, 6842, 7893, 16125, 17914, 24286, 29823, 32522, 32675, 8854, 12328, 16023, 19887, 21302, 21992, 22417, 24235, 27088, 31981, 813, 1546, 9749, 13315, 16494, 18194, 21170, 25090, 27244, 28379, 1686, 3297, 3428, 3959, 7485, 14743, 22947, 23786, 24477, 30093, 1348, 4384, 9208, 13456, 14489, 19231, 19534, 26522, 29822, 30582, 1188, 4459, 4662, 5052, 5302, 9732, 18247, 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_100_Almost_Sorted_0_1 {
            get {
                return ResourceManager.GetString("Array_100_Almost_Sorted_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [503, 1959, 2112, 5963, 6524, 6725, 9402, 10704, 11269, 11498, 14517, 20073, 21720, 24391, 25008, 26640, 28342, 28805, 30089, 30637, 3966, 9365, 10344, 10931, 10999, 11051, 13617, 13717, 14127, 17262, 18915, 18955, 23253, 23948, 27834, 28952, 30585, 31902, 31946, 32453, 3219, 3236, 3659, 4011, 7921, 8733, 14521, 14716, 15856, 16694, 17455, 18095, 22150, 22376, 22702, 27743, 27816, 28043, 29985, 32518, 873, 2476, 2982, 6035, 6168, 7174, 7216, 9925, 11393, 12615, 14514, 17768, 18005, 20659, 21285, 23006, 2471 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_100_Almost_Sorted_0_2 {
            get {
                return ResourceManager.GetString("Array_100_Almost_Sorted_0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2904, 3009, 3878, 5192, 8192, 9806, 11169, 11508, 11691, 12152, 12430, 13652, 13663, 14117, 14580, 15285, 15988, 18047, 21179, 21212, 21989, 23507, 23840, 24157, 25240, 25327, 27496, 28361, 29042, 31902, 31985, 32163, 32367, 472, 856, 1823, 2360, 6321, 8224, 9235, 9339, 10077, 12654, 15883, 16137, 17503, 18067, 18443, 18799, 20547, 22263, 22870, 23301, 23851, 24005, 24533, 24719, 25016, 26157, 26243, 27370, 28097, 29144, 29498, 30605, 31245, 1176, 1214, 1219, 1307, 1887, 2661, 3397, 3932, 3950, 5855, 6351, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_100_Almost_Sorted_0_33 {
            get {
                return ResourceManager.GetString("Array_100_Almost_Sorted_0_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [1295, 1428, 1557, 3009, 3335, 4662, 4698, 6392, 6528, 7158, 7162, 10380, 10440, 11873, 11954, 12194, 12725, 12967, 13710, 13912, 14256, 14646, 15186, 15911, 17702, 18052, 18907, 19704, 20239, 21438, 21854, 23637, 23982, 26209, 27015, 27665, 28853, 29724, 30237, 32560, 1292, 3096, 3285, 3370, 3528, 3824, 3986, 4046, 7739, 8255, 9215, 9613, 10799, 11675, 16997, 17074, 17593, 17999, 21135, 21228, 21408, 22330, 22415, 22707, 22813, 23575, 23781, 24434, 24774, 25943, 26774, 26980, 27410, 28023, 30012, 30033, 30 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_100_Almost_Sorted_0_4 {
            get {
                return ResourceManager.GetString("Array_100_Almost_Sorted_0_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [190, 1750, 2574, 4016, 4215, 4365, 6001, 7112, 7435, 7806, 10104, 11242, 11439, 12093, 12577, 13004, 13157, 13402, 13950, 13952, 15331, 15427, 16044, 16593, 17884, 18100, 18103, 18106, 18300, 18716, 19856, 21109, 21520, 22589, 23905, 24244, 24446, 25248, 25905, 26021, 26121, 26359, 26649, 27274, 28631, 28850, 30627, 31424, 31949, 32732, 107, 552, 584, 620, 2093, 2124, 2755, 3047, 3070, 4915, 6725, 6954, 7669, 8930, 8986, 9074, 10567, 11097, 11718, 12551, 12572, 13610, 13723, 14037, 15426, 16111, 16436, 180 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_100_Almost_Sorted_0_5 {
            get {
                return ResourceManager.GetString("Array_100_Almost_Sorted_0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [16431, 20920, 2813, 20001, 16733, 11486, 15890, 26661, 1753, 28710, 6284, 13458, 8970, 26719, 1280, 20332, 28622, 13364, 25493, 20570, 31926, 30944, 4438, 2970, 9754, 22114, 25057, 27159, 17793, 3419, 20290, 6860, 27592, 7774, 4247, 7202, 24350, 11768, 20468, 2216, 13645, 25473, 24717, 22423, 26365, 13134, 18895, 24006, 30377, 28926, 18787, 24241, 5505, 13792, 18074, 19910, 12061, 8600, 11403, 30267, 4402, 31780, 30464, 26964, 25641, 30159, 3934, 12622, 17364, 4318, 9364, 3843, 10559, 32508, 6635, 17303, 1 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_100_Random {
            get {
                return ResourceManager.GetString("Array_100_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [32661, 31645, 31461, 31109, 30559, 30274, 28968, 28722, 28486, 27974, 27969, 27866, 27709, 27599, 27596, 27506, 27029, 26979, 26686, 26401, 26035, 26020, 25920, 25750, 25612, 25350, 24999, 24461, 23903, 23299, 23286, 23279, 23236, 22949, 22900, 21555, 20601, 20323, 19728, 19604, 19083, 18626, 18576, 18222, 17984, 17422, 17377, 17291, 17228, 16423, 15930, 15737, 15633, 14839, 14100, 13957, 13347, 13031, 12695, 12521, 12367, 11361, 11065, 10962, 10912, 10811, 10070, 9985, 9979, 9589, 9523, 9373, 9206, 9202,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_100_Reverse_Sorted {
            get {
                return ResourceManager.GetString("Array_100_Reverse_Sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [321, 775, 1224, 1319, 1422, 1479, 1640, 2956, 3015, 3369, 3860, 4347, 5448, 6328, 6497, 6506, 7024, 7031, 7365, 7491, 7814, 7944, 7945, 8132, 8304, 8931, 9245, 9470, 9909, 10234, 10384, 10471, 10513, 10941, 11240, 11412, 12776, 13339, 13440, 13772, 14236, 14276, 14553, 14555, 15011, 15466, 16129, 16165, 16409, 16534, 16623, 16772, 17023, 17122, 17662, 17746, 18030, 18655, 19511, 20045, 20372, 20409, 20535, 20781, 21276, 21392, 21722, 21863, 21873, 22037, 22098, 22281, 22528, 23291, 23364, 23471, 23600, 237 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_1000_Almost_Sorted_0_1 {
            get {
                return ResourceManager.GetString("Array_1000_Almost_Sorted_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [15, 189, 446, 543, 805, 900, 1164, 1954, 2028, 2075, 2137, 2676, 2849, 2974, 3064, 3072, 3144, 3432, 3518, 4124, 4350, 4350, 4577, 4653, 4748, 4873, 5062, 5171, 5217, 5658, 5728, 5871, 6125, 6178, 6340, 6438, 6559, 6648, 6729, 6756, 6821, 6958, 7213, 7360, 7376, 7524, 7554, 7760, 7990, 8146, 8541, 8570, 8772, 8812, 9268, 9336, 9572, 9655, 9879, 9913, 10432, 10487, 10629, 10726, 10888, 11163, 11340, 11403, 11421, 11575, 11721, 11792, 12202, 12250, 12327, 12506, 12717, 12725, 12834, 12853, 12937, 13134, 1328 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_1000_Almost_Sorted_0_2 {
            get {
                return ResourceManager.GetString("Array_1000_Almost_Sorted_0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [72, 246, 357, 361, 599, 834, 1182, 1283, 1521, 1538, 1590, 1642, 1642, 1672, 1704, 1743, 2059, 2099, 2297, 2379, 2598, 2680, 2789, 3039, 3146, 3296, 3395, 3407, 3433, 3460, 3543, 3578, 3700, 3718, 3726, 3757, 3974, 4001, 4099, 4152, 4180, 4326, 4519, 4596, 4603, 4605, 4868, 4886, 5006, 5038, 5234, 5305, 5383, 5415, 5420, 5544, 5602, 5814, 5836, 5939, 5944, 5946, 6023, 6044, 6106, 6284, 6312, 6470, 6587, 6695, 6733, 6808, 6813, 6880, 6924, 7084, 7118, 7126, 7162, 7182, 7396, 7614, 7890, 8120, 8244, 8428, 84 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_1000_Almost_Sorted_0_33 {
            get {
                return ResourceManager.GetString("Array_1000_Almost_Sorted_0_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [0, 150, 181, 296, 396, 678, 782, 787, 799, 925, 978, 990, 1042, 1058, 1075, 1110, 1178, 1205, 1269, 1349, 1396, 1482, 1527, 1550, 1740, 1752, 1803, 1834, 1864, 1884, 1918, 1983, 2015, 2136, 2143, 2407, 2408, 2455, 2501, 2535, 2608, 2679, 2732, 2910, 2948, 3077, 3242, 3509, 3679, 3700, 3808, 4066, 4072, 4097, 4406, 4428, 4478, 4489, 4522, 4680, 4816, 4832, 5053, 5059, 5070, 5154, 5206, 5249, 5465, 5474, 5555, 5610, 5632, 5794, 5818, 5823, 5834, 6006, 6009, 6170, 6272, 6351, 6414, 6568, 6569, 6689, 6693, 673 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_1000_Almost_Sorted_0_4 {
            get {
                return ResourceManager.GetString("Array_1000_Almost_Sorted_0_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [56, 95, 108, 132, 295, 332, 367, 394, 503, 515, 566, 619, 630, 679, 690, 782, 901, 906, 923, 934, 960, 1013, 1030, 1175, 1219, 1269, 1533, 1642, 1775, 1823, 1841, 2079, 2089, 2189, 2272, 2303, 2344, 2459, 2490, 2522, 2645, 2728, 2797, 2806, 2858, 2867, 2883, 2915, 2972, 3050, 3050, 3066, 3068, 3141, 3296, 3357, 3642, 3859, 3902, 4065, 4072, 4100, 4104, 4127, 4166, 4188, 4188, 4193, 4202, 4219, 4231, 4246, 4247, 4290, 4308, 4330, 4439, 4480, 4496, 4717, 4733, 4776, 4779, 4887, 4904, 4963, 4989, 5081, 5107,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_1000_Almost_Sorted_0_5 {
            get {
                return ResourceManager.GetString("Array_1000_Almost_Sorted_0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [18578, 10322, 13785, 16465, 26190, 13563, 29208, 13995, 4784, 11944, 7114, 28297, 5267, 29194, 12499, 836, 14520, 25784, 18277, 1293, 28555, 21586, 4141, 30789, 12202, 19950, 26865, 22269, 8616, 1841, 4102, 3630, 15159, 3383, 3103, 9586, 29147, 32164, 26521, 30631, 8154, 22892, 28050, 682, 4534, 24531, 11144, 31036, 3905, 234, 22182, 31157, 4379, 6545, 8769, 23229, 21364, 26161, 8093, 7165, 8269, 5424, 30728, 7753, 10044, 7279, 3269, 13567, 5855, 32565, 7221, 31799, 7377, 28734, 5929, 11341, 3254, 10464, 2 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_1000_Random {
            get {
                return ResourceManager.GetString("Array_1000_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [32751, 32714, 32708, 32630, 32560, 32483, 32357, 32320, 32262, 32255, 32165, 32165, 32157, 31984, 31976, 31970, 31962, 31934, 31926, 31857, 31854, 31828, 31809, 31802, 31791, 31778, 31731, 31660, 31590, 31582, 31536, 31502, 31491, 31437, 31408, 31388, 31378, 31271, 31260, 31160, 31149, 31113, 31025, 31023, 31006, 30986, 30975, 30960, 30924, 30917, 30912, 30902, 30867, 30865, 30800, 30754, 30698, 30697, 30690, 30673, 30665, 30657, 30610, 30601, 30585, 30519, 30518, 30500, 30493, 30483, 30470, 30433, 30411,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_1000_Reverse_Sorted {
            get {
                return ResourceManager.GetString("Array_1000_Reverse_Sorted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [13, 14, 21, 26, 46, 65, 86, 89, 93, 102, 219, 244, 257, 280, 292, 304, 312, 334, 347, 419, 439, 515, 531, 555, 565, 584, 607, 714, 733, 822, 854, 885, 948, 1040, 1075, 1119, 1124, 1133, 1145, 1170, 1277, 1281, 1311, 1334, 1335, 1390, 1606, 1611, 1635, 1636, 1674, 1755, 1776, 1853, 1900, 1918, 1927, 1960, 2040, 2148, 2157, 2213, 2233, 2302, 2362, 2415, 2588, 2611, 2711, 2732, 2738, 2823, 2825, 2832, 2843, 2882, 2885, 2920, 2959, 2963, 3045, 3083, 3108, 3113, 3174, 3193, 3199, 3230, 3231, 3242, 3260, 3337, 3 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_10000_Almost_Sorted_0_1 {
            get {
                return ResourceManager.GetString("Array_10000_Almost_Sorted_0_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [12, 16, 19, 30, 45, 46, 47, 62, 67, 81, 83, 94, 121, 128, 129, 147, 150, 161, 179, 212, 237, 238, 261, 277, 277, 303, 350, 356, 381, 413, 422, 422, 484, 491, 506, 527, 554, 558, 580, 581, 630, 643, 684, 690, 704, 706, 717, 751, 766, 773, 785, 818, 818, 827, 831, 852, 882, 902, 919, 921, 932, 932, 941, 961, 970, 987, 994, 1006, 1052, 1068, 1072, 1078, 1104, 1104, 1108, 1128, 1153, 1170, 1198, 1207, 1214, 1215, 1233, 1240, 1242, 1244, 1245, 1248, 1261, 1270, 1275, 1282, 1301, 1320, 1329, 1330, 1341, 1356, 13 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_10000_Almost_Sorted_0_2 {
            get {
                return ResourceManager.GetString("Array_10000_Almost_Sorted_0_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [38, 43, 48, 58, 69, 71, 108, 113, 117, 179, 180, 191, 210, 214, 232, 249, 250, 258, 273, 276, 283, 283, 326, 330, 330, 337, 341, 377, 382, 387, 390, 392, 400, 401, 409, 418, 432, 437, 439, 447, 519, 520, 520, 521, 521, 522, 532, 536, 555, 557, 567, 570, 575, 579, 591, 593, 606, 616, 643, 644, 650, 659, 676, 681, 684, 700, 701, 710, 721, 724, 725, 727, 735, 748, 763, 765, 778, 779, 798, 801, 825, 830, 831, 855, 859, 860, 889, 892, 893, 922, 935, 936, 940, 949, 955, 972, 984, 997, 1010, 1015, 1022, 1022, 107 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_10000_Almost_Sorted_0_33 {
            get {
                return ResourceManager.GetString("Array_10000_Almost_Sorted_0_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [2, 6, 15, 19, 28, 34, 38, 47, 64, 65, 67, 70, 78, 79, 86, 87, 99, 101, 102, 106, 111, 112, 134, 152, 163, 169, 183, 190, 190, 192, 195, 200, 240, 261, 262, 272, 274, 287, 293, 297, 299, 301, 302, 310, 331, 345, 350, 357, 357, 362, 402, 405, 414, 451, 472, 476, 491, 492, 502, 507, 508, 511, 511, 514, 516, 519, 535, 537, 540, 548, 554, 556, 560, 565, 578, 579, 582, 585, 600, 610, 630, 631, 633, 634, 635, 636, 640, 647, 663, 675, 684, 688, 691, 697, 714, 719, 720, 721, 725, 739, 755, 755, 756, 761, 772, 776,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_10000_Almost_Sorted_0_4 {
            get {
                return ResourceManager.GetString("Array_10000_Almost_Sorted_0_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [7, 9, 9, 11, 16, 18, 29, 34, 36, 40, 49, 51, 72, 93, 96, 101, 112, 113, 114, 119, 125, 125, 136, 148, 154, 155, 165, 166, 166, 167, 168, 172, 172, 172, 173, 178, 180, 185, 188, 189, 194, 194, 196, 199, 199, 203, 205, 232, 232, 233, 250, 264, 270, 272, 275, 276, 290, 294, 298, 309, 314, 317, 327, 328, 338, 346, 355, 387, 389, 407, 413, 428, 429, 451, 452, 453, 455, 455, 467, 476, 480, 484, 495, 513, 516, 517, 524, 530, 530, 556, 559, 569, 571, 577, 594, 606, 607, 618, 620, 620, 623, 624, 628, 628, 637, 640, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_10000_Almost_Sorted_0_5 {
            get {
                return ResourceManager.GetString("Array_10000_Almost_Sorted_0_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [28129, 13865, 2580, 1435, 26742, 18915, 29425, 5318, 27012, 403, 26593, 30487, 14565, 26968, 32322, 3382, 4547, 15834, 16177, 1916, 10124, 3890, 24462, 26742, 23522, 4120, 28536, 25676, 8789, 14258, 30729, 14900, 17204, 9317, 24898, 20537, 1167, 26818, 6967, 2701, 28545, 30798, 24991, 2172, 32599, 28070, 30250, 176, 9999, 1650, 32682, 26228, 14130, 24395, 29303, 14499, 21136, 9052, 19222, 25336, 10384, 15573, 14393, 25099, 2706, 21614, 1501, 29535, 27309, 5097, 6698, 31708, 16189, 10613, 13956, 4700, 21818 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_10000_Random {
            get {
                return ResourceManager.GetString("Array_10000_Random", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [32764, 32760, 32760, 32759, 32752, 32750, 32744, 32735, 32735, 32731, 32728, 32714, 32712, 32710, 32710, 32702, 32699, 32697, 32696, 32692, 32688, 32687, 32686, 32685, 32680, 32678, 32672, 32672, 32665, 32654, 32648, 32645, 32642, 32634, 32630, 32628, 32626, 32623, 32619, 32607, 32601, 32596, 32586, 32585, 32584, 32577, 32576, 32575, 32572, 32570, 32567, 32558, 32555, 32555, 32552, 32552, 32549, 32546, 32540, 32539, 32538, 32533, 32532, 32529, 32526, 32525, 32524, 32522, 32503, 32500, 32500, 32497, 32496,  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Array_10000_Reverse_Sorted {
            get {
                return ResourceManager.GetString("Array_10000_Reverse_Sorted", resourceCulture);
            }
        }
    }
}
